version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    volumes:
      - ../../models:/models

  app:
    build:
      context: ./app
    ports:
      - "8501:8501"
    depends_on:
      - api
